E(fblog.c)$weight <- 1
library(igraph)
install.packages("igraph")
library(igraph)
g <- graph_from_literal(1-2, 1-3, 2-3, 2-4, 3-5, 4-5, 4-6, 4-7, 5-6, 5-7)
V(g)
E(g)
print_all(g)
plot(g)
dg <- plot_from_literal(1-+2, 1-+3, 2++3)
dg <- graph_from_literal(1-+2, 1-+3, 2++3)
plot(dg)
dg <- graph_from_literal(Sam-+Mary, Sam-+Tom, Mary++Tom)
print_all(dg)
V(dg)$name <- c("Sam", "Mary", "Tom")
E(dg)
as_adjacency_matrix(g)
h <- induced_subgraph(g, 1:5)
print_all(h)
h <- g - vertices(c(6,7))
h <- h + vertices(c(6,7))
g <- h + edges(c(4,6), c(4,7), c(5,6), c(6,7))
h1 <- h
h2 <- graph_from_literal(4-6, 4-7, 5-6, 6-7)
g <- union(h1, h2)
V(dg)$name
V(dg)$gender <- c("M", "F", "M")
V(g)$color <- "red"
is_weighted(g)
wg <- g
E(wg)$weight <- runif(ecount(wg))
is_weighted(wg)
g$name <- "Toy Graph"
library(sand)
install.packages("sand")
library(sand)
g.lazega <- graph_from_data_frame((elist.lazega, directed= "FALSE", vertices = v.attr.lazega))
g.lazega <- graph_from_data_frame(elist.lazega, directed="FALSE", vertices = v.attr.lazega)
g.lazega$name <- "Lazega lawyers"
vcount(g.lazega)
ecount(g.lazega)
vertex_attr_names(g.lazega)
is_simple(g)
mg <- g + edge(2,3)
print_all(g)
print_all(mg)
is_simple(mg)
E(mg)$weight <- 1
wg2 <- simplify(mg)
is_simple(wg2)
print_all(wg2)
E(wg2)$weight
neighbors(g, 5)
degree(g)
degree(dg, mode="in")
degree(dg, mode="out")
is_connected(g)
clusters(g)
is_connected(dg, mode="weak")
diameter(g, weights=NA)
g.full <- make_full_graph(7)
g.ring <- make_ring(7)
g.tree <- make_tree(7, children=2, mode="undirected")
g.star <- make_star(7, mode="undirected")
par(mfrow=c(2,2), mai = c(0.2, 0.2, 0.2, 0.2))
plot(g.full)
plot(g.ring)
plot(g.tree)
plot(g.star)
is_dag(dg)
library(igraphdata)
data(karate)
set.seed(42)
1 <- layout_with_kk(karate)
l <- layout_with_kk(karate)
igraph_options(vertex.size=10)
par(mfrow=c(1,1))
plot(karate, layout=1, vertex.label=V(karate))
plot(karate, layout=l, vertex.label=V(karate))
plot(karate, layout=l, vertex.label=V(karate), vertex.color=NA)
V(karate)$label <- sub("actor", "", V(karate)$name)
V(karate)$shape <- "circle"
library(sand)
data(lazega)
colbar <- c("red", "dodgerblue", "goldenrod")
v.colors <- colbar[V(lazega)$Office]
v.shapes <- c("circle", "square")[V(lazega)$Practice]
v.size <- 3.5*sqrt(V(lazega)$Years)
v.label <- V(lazega)$seniority
set.seed(42)
l <- layout_with_fr(lazega)
plot(lazega, layout=l, vertex.color = v.colors, vertex.shape = v.shapes, vertex.size = v.size, vertex.label = v.label)
library(sand)
summary(fblog)
party.names <- sort(unique(V(fblog)$PolParty))
party.names
set.seed(42)
l = layout_with_kk(fblog)
party.nums.f <- as.factor(V(fblog)$PolParty)
party.nums <- as.numeric(party.nums.f)
library(RColorBrewer)
colrs < - brewer.pal(9, "Set1")
brewer.pal(9, "Set1")
colrs <- brewer.pal(9, "Set1")
V(fblog)$color <-colrs(party.nums)
V(fblog)$color <-colrs[party.nums]
plot(fblog, layout=l, vertex.label=NA, vertex.size=3)
set.seed(42)
l <- layout_with_drl(fblog)
plot(fblog, layout=l, vertex.size=5, vertex.label=NA)
fblog.c <- contract(fblog, party.nums)
E(fblog.c)$weight <- 1
fblog.c <- simplify(fblog.c)
party.size <- as.vector(table(V(fblog)$PolParty))
plot(fblog.c, vertex.size=5*sqrt(party.size),vertex.label=party.names, vertex.color=colrs,edge.width=sqrt(E(fblog.c)$weight),vertex.label.dist=3.5, edge.arrow.size=0)
data(karate)
k.nbhds <- make_ego_graph(karate, order=1)
sapply(k.nbhds, vcount)
k.1 <- k.nbhds[[1]]
k.34 <- k.nbhds[[34]]
par(mfrow=c(1,2))
plot(k.1,vertex.label=NA, vertex.color=c("red", rep("lightblue", 16)))
plot(k.34, vertex.label=NA,vertex.color=c(rep("lightblue",17),"red"))
View(g.full)
